# Generated by Django 3.0.8 on 2020-09-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_all_listing_auction_listing_bids_close_bid_watch_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
