# Generated by Django 3.0.8 on 2020-09-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200918_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_ID', models.IntegerField()),
                ('p_ID', models.IntegerField()),
            ],
        ),
    ]
