# Generated by Django 3.0.8 on 2020-09-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200902_1323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auction_listing',
            new_name='Active_listing',
        ),
    ]
