# Generated by Django 3.0.8 on 2020-09-14 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200914_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='active_listing',
            old_name='title_name',
            new_name='item_name',
        ),
    ]
