# Generated by Django 3.0.8 on 2020-09-17 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200917_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch_list',
            name='product_ID',
        ),
        migrations.AddField(
            model_name='watch_list',
            name='product_ID',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Watch_List', to='auctions.Product'),
        ),
        migrations.RemoveField(
            model_name='watch_list',
            name='user_ID',
        ),
        migrations.AddField(
            model_name='watch_list',
            name='user_ID',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
