# Generated by Django 2.2.14 on 2020-09-26 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comment_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comment_Table',
        ),
    ]
