# Generated by Django 3.0.8 on 2020-09-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200917_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch_list',
            name='product_ID',
        ),
        migrations.RemoveField(
            model_name='watch_list',
            name='user_ID',
        ),
    ]
