# Generated by Django 2.2.14 on 2020-09-29 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200926_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bid', models.IntegerField()),
                ('bid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_bids', to=settings.AUTH_USER_MODEL)),
                ('on_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bid', to='auctions.Product')),
            ],
        ),
    ]
