# Generated by Django 3.0.8 on 2020-09-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200915_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_listing',
            name='owner_name',
            field=models.CharField(max_length=64),
        ),
    ]
