# Generated by Django 2.2.14 on 2020-09-29 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Won',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=64)),
                ('item_name', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, max_length=64)),
                ('link', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('time', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='winner',
            name='product_won',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_won', to='auctions.All_Won'),
        ),
    ]
