# Generated by Django 3.0.8 on 2020-09-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200915_1930'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Active_listing',
            new_name='Products',
        ),
    ]
