# Generated by Django 3.0.8 on 2020-09-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200916_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='item_name',
            new_name='product_name',
        ),
        migrations.AddField(
            model_name='watch_list',
            name='Product_name',
            field=models.ManyToManyField(blank=True, related_name='Watch_List', to='auctions.Products'),
        ),
    ]
