# Generated by Django 3.0.8 on 2020-09-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200916_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='item_name',
        ),
        migrations.RemoveField(
            model_name='watch_list',
            name='Product_name',
        ),
    ]
