# Generated by Django 3.0.8 on 2020-09-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_watch_list_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch_list',
            name='user_name',
        ),
        migrations.AddField(
            model_name='watch_list',
            name='user_name',
            field=models.ManyToManyField(blank=True, related_name='user_name', to='auctions.Product'),
        ),
    ]
