# Generated by Django 3.0.8 on 2020-09-16 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20200916_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch_list',
            name='user_name',
            field=models.ManyToManyField(blank=True, related_name='user_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
