# Generated by Django 3.0.8 on 2020-09-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20200916_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch_list',
            name='listing_ID',
        ),
    ]
